### ISSUE TITLE
How to show help when called without arguments.

### ISSUE THREAD

**Issue by dhilst** [kutoga/FluentArgs#41]
Hi, Nice work and API

I follow the readme and I'll need something like this

````
        public static void Main(string[] args)
        {
            FluentArgsBuilder.New()
                .DefaultConfigsWithAppDescription("nisi-backend tools")
                .Given.Flag("-v", "--version").Then(() => Console.WriteLine($"Program version: ${VERSION}"))
                .Given.Command("-c", "--command")
                    .HasValue("import-csv").Then(b => b
                        .Parameter<string>("-d", "--database")
                            .WithDescription("Database connection")
                            .IsRequired()
                        .Call(database => Console.WriteLine($"Hello {database}")))
                    .ElseIsInvalid()
                .Invalid()
                .Parse(args)
                ;
        }
```

I like to show help messages when no arguments are provided, so as a user I can simply run the command (even without `--help` and get help`

Currently the code is throwing this exception

```➜
Unhandled exception. System.Exception: TODO: Invalid state: show helP
   at FluentArgs.Execution.InvalidStep.Execute(State state)
   at FluentArgs.Execution.GivenCommandStep.Execute(State state)
   at FluentArgs.Execution.GivenFlagStep.Execute(State state)
   at FluentArgs.Execution.InitialStep.Execute(State state)
   at FluentArgs.FluentArgsDefinition.ParseFromState(State state)
   at FluentArgs.FluentArgsDefinition.Parse(String[] args)
   at FluentArgs.ICallableExtensions.Parse(IBuildable buildable, String[] args)
   at tools.Program.Main(String[] args) in /Users/gecko/code/nisi-backend/tools/Program.cs:line 12
```

Regards

**Comment by kutoga** [comment]
The following PR adds a hint for the help:
https://github.com/kutoga/FluentArgs/pull/42

It does not directly show the help, but it uses similar hints like for other invalid inputs. Probably, it makes sense to add an option which shows the help directly. Currently, the output looks like this:
![image](https://user-images.githubusercontent.com/19676199/91663120-307c0300-eae7-11ea-9378-8f13ee59e872.png)
